# Generated by Django 2.2.18 on 2021-02-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0004_auto_20201120_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="client_domain",
            field=models.TextField(blank=True, null=True),
        ),
    ]
